package com.example.appevo09

class Vehicle ( val numInventari: Int,
                val ambit: String?,
                val colleccio: String?,
                val nom: String,
                val llocFabricacio: String?,
                val procedencia: String?,
                val fontEnergia: String?,
                val potencia: String?,
                val formaIngres: String?,
                val fontIngres: String?,
                val multimedia : MutableList<String>,
                val descripcio: String,
                val any: Int,
                val cicle: Int?,
                val cilindrada: Int?,
                val velocitatMax: Int?,
                val velocitatCreuer: Int?,
                val capacitatDeposit: Int?,
                val llongitud: Float?,
                val alcada: Float?,
                val envergadura: Float?,

)